# BEGIN_KITTY_THEME
background #022B00
foreground #0BFF00
cursor #0BFF00

selection_background  #2a9b34
color0                #1e1e1e
color8                #016d27
color1                #fb0029
color9                #a6ff3e
color2                #0BFF00
color10               #9fff6d
color3                #649a25
color11               #d1ff6d
color4                #149b45
color12               #72ffb5
color5                #53b82b
color13               #50ff3d
color6                #2bb767
color14               #22ff71
color7                #dffeee
color15               #daeed0
selection_foreground  #3a3c30

ecursor_shape block
shell_integration no-cursor
cursor_blink_interval 0.5
cursor_stop_blinking_after 0
# END_KITTY_THEME
#
tab_bar_style powerline
tab_bar_edge bottom
# inactive_tab_background #e06c75
# active_tab_background #98c379
# inactive_tab_foreground #000000
# tab_bar_margin_color black

background_opacity 0.85
# background_image ./tapety-apple-1.jpg
background_image_layout scaled
background_blur 50
dynamic_background_opacity yes

# font_family MesloLGS NF
font_family      family="ShureTechMono Nerd Font Mono Regular"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 18

enable_audio_bell no
# url_color #61afef
url_style curly

# Para moverme en el tmux
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down 

#copy/paste de varios buffers
map f1 copy_to_buffer a
map f2 paste_from_buffer a
map f3 copy_to_buffer b
map f4 paste_from_buffer b

cursor_beam_thickness 1.8

mouse_hide_wait 3.0
detect_urls yes

repaint_delay 10
input_delay 3
sync_to_monitor yes

map ctrl+shift+z toggle_layout stack

map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd

shell zsh



# Added by Gogh
